name: release

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push 'release'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            PROFILE=release
            SITE_ROOT=https://blog.weberc2.com
          push: true
          tags: |
            weberc2/blog:latest
            weberc2/blog:${{ github.sha }}
            weberc2/blog:release
            weberc2/blog:release-${{ github.sha }}
      - name: Build and push 'internal'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            PROFILE=internal
            SITE_ROOT=https://blog.falcon-atlas.ts.net
          push: true
          tags: |
            weberc2/blog:internal
            weberc2/blog:internal-${{ github.sha }}